/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package kh.parkinggarageapp;

import java.util.Calendar;

/**
 * Holds timestamp information for when a car enters or leaves the garage
 * @author khalloway
 */
public class Ticket {
    /**
     * Class variables for start and end times of the ticket. Stored as separate
     * hour and minute variables for calculating time passed. 
     * Has a feeStrategy for calculating the amount owed.
     */
//    private double startHour;
//    private double startMin;
//    private double endHour;
//    private double endMin;
    private Calendar start;
    private Calendar end;
    
//    /**
//     * Ticket constructor that takes the time that the ticket was issued as arguments.
//     * For testing purposes.
//     * @param startHour
//     * @param startMin 
//     */
//    public Ticket(double startHour, double startMin){
//        this.setStartHour(startHour);
//        this.setStartMin(startMin);
//    }
    
    /**
     * Ticket Constructor
     * @param start Calendar object representing when the car entered;
     * @param end Calendar object representing when the car exited;
     */
    public Ticket(Calendar start, Calendar end){
        this.setStart(start);
        this.setEnd(end);
    }
    
    
//    
//    /**
//     * Generic ticket constructor. Will be used to initialize a new ticket, which 
//     * will be generated by the punchIn() method. Every punchIn() must be followed
//     * by a punchOut().
//     */
//    public Ticket(){
//        this.setStartHour(0);
//        this.setStartMin(0);
//        this.setEndHour(0);
//        this.setEndMin(0);
//    }
//    
//    /**
//     * Sets the start time of the Ticket.
//     * @param startHour
//     * @param startMin 
//     */
//    public void punchIn(double startHour, double startMin){
//        this.setStartHour(startHour);
//        this.setStartMin(startMin);
//    }
//    
//    /**
//     * Sets the ending time of the ticket.
//     * @param endHour
//     * @param endMin 
//     */
//    public void punchOut(double endHour, double endMin){
//        this.setEndHour(endHour);
//        this.setEndMin(endMin);
//    }
//
//    /**
//     * 
//     * Getters and setters
//     */
//    public double getStartHour() {
//        return startHour;
//    }
//
//    public void setStartHour(double startHour) {
//        this.startHour = startHour;
//    }
//
//    public double getStartMin() {
//        return startMin;
//    }
//
//    public void setStartMin(double startMin) {
//        this.startMin = startMin;
//    }
//
//    public double getEndHour() {
//        return endHour;
//    }
//
//    public void setEndHour(double endHour) {
//        this.endHour = endHour;
//    }
//
//    public double getEndMin() {
//        return endMin;
//    }
//
//    public void setEndMin(double endMin) {
//        this.endMin = endMin;
//    }

    public Calendar getStart() {
        return start;
    }

    public void setStart(Calendar start) {
        this.start = start;
    }

    public Calendar getEnd() {
        return end;
    }

    public void setEnd(Calendar end) {
        this.end = end;
    }
    
    
    
}
