/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package kh.parkinggarageapp;

import java.util.Calendar;
import java.util.Objects;

/**
 * Holds timestamp information for when a car enters or leaves the garage
 * @author khalloway
 */
public class Ticket {
    /**
     * Class variables for start and end times of the ticket. Stored as two Calendar objects
     * Has a feeStrategy for calculating the amount owed.
     */
    private Calendar start;
    private Calendar end;
    private DateTimeStrat dts;
    
    
    /**
     * Ticket Constructor
     * @param start Calendar object representing when the car entered;
     * @param end Calendar object representing when the car exited;
     */
    public Ticket(Calendar start, Calendar end, DateTimeStrat dts){
        this.setStart(start);
        this.setEnd(end);
        this.setDts(dts);
    }
    
    /**
     * Generic ticket constructor. Will be used to initialize a new ticket, which 
     * will be generated by the punchIn() method. Every punchIn() must be followed
     * by a punchOut().
     */
    public Ticket(){}
    
    /**
     * Sets the start time of the Ticket.
     * @param start
     */
    public void punchIn(Calendar start){
        this.setStart(start);
    }
    
    /**
     * Sets the ending time of the ticket.
     * @param end
     */
    public void punchOut(Calendar end){
        this.setEnd(end);
    }
    
    public PunchTime getTimePunched(){
        return dts.getTimeDiff(start, end);
    }

    /**
     * 
     * Getters and setters
     */
    public Calendar getStart() {
        return start;
    }

    public void setStart(Calendar start) {
        this.start = start;
    }

    public Calendar getEnd() {
        return end;
    }

    public void setEnd(Calendar end) {
        this.end = end;
    }

    public DateTimeStrat getDts() {
        return dts;
    }

    public void setDts(DateTimeStrat dts) {
        this.dts = dts;
    }

    @Override
    public String toString() {
        return "Ticket{" + "start=" + start + ", end=" + end + ", dts=" + dts + '}';
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 11 * hash + Objects.hashCode(this.start);
        hash = 11 * hash + Objects.hashCode(this.end);
        hash = 11 * hash + Objects.hashCode(this.dts);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Ticket other = (Ticket) obj;
        if (!Objects.equals(this.start, other.start)) {
            return false;
        }
        if (!Objects.equals(this.end, other.end)) {
            return false;
        }
        if (!Objects.equals(this.dts, other.dts)) {
            return false;
        }
        return true;
    }
    
    
    
    
    
}
